# Generated by Django 5.1.7 on 2025-03-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_customuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="bli02",
            field=models.FileField(blank=True, null=True, upload_to="bli02/"),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="bli03",
            field=models.FileField(blank=True, null=True, upload_to="bli03/"),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="bli04",
            field=models.FileField(blank=True, null=True, upload_to="bli04/"),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="bli08",
            field=models.FileField(blank=True, null=True, upload_to="bli08/"),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="bli09",
            field=models.FileField(blank=True, null=True, upload_to="bli09/"),
        ),
    ]
