# Generated by Django 5.1.7 on 2025-03-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_studentprofile_bli02_studentprofile_bli03_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="bli02",
            field=models.FileField(
                blank=True,
                help_text="Borang Jawapan Industri",
                null=True,
                upload_to="bli02/",
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="bli03",
            field=models.FileField(
                blank=True,
                help_text="Surat Perjanjian Latihan Industri",
                null=True,
                upload_to="bli03/",
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="bli04",
            field=models.FileField(
                blank=True,
                help_text="Borang Akuan Lapor Diri Untuk Latihan Industri di Organisasi",
                null=True,
                upload_to="bli04/",
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="bli08",
            field=models.FileField(
                blank=True,
                help_text="Borang Penialainan Penyelia Akademik",
                null=True,
                upload_to="bli08/",
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="bli09",
            field=models.FileField(
                blank=True,
                help_text="Borang Penilaian Penyelia Industri",
                null=True,
                upload_to="bli09/",
            ),
        ),
    ]
