# Generated by Django 5.1.7 on 2025-03-21 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("postcode", models.CharField(max_length=10)),
                ("category", models.CharField(max_length=100)),
                ("allowance", models.DecimalField(decimal_places=2, max_digits=10)),
                ("blacklisted", models.BooleanField(default=False)),
                ("remarks", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
